# -*- coding: utf-8 -*-
"""Latihanpip.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ag8zoXpxGPAcF6SjngPlPMRwh5S8eH5u
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

URL = "https://www.bukalapak.com/c/komputer/laptop?from=nav_header"
page = requests.get(URL)

SOUP = BeautifulSoup(page.content, "html.parser")
produk = SOUP.find_all("div", "bl-product-card__description")

data = []
for item in produk:
  nama = item.select(".bl-product-card__description-name")
  price = item.select(".bl-product-card__description-price p")
  data.append({"nama": nama[0].text.strip(), "harga": price[0].text.strip()})

#print data
df = pd.DataFrame(data)
print(df)